languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "日本語メモ"
logo = "img/logo.png"
description = "我的日语笔记本"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2006-01-02"

[author]
  name = "小綿尾巴"
  image = "img/avatar.jpeg"
  # headline = "I'm only human"
  bio = "学日本語的前端工程师"