# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "fire"
defaultAppearance = "dark" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["n2"]
# robots = ""

[header]
  layout = "basic"

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "page" # valid options: page, profile, custom
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/n2"
  cardView = false
  cardViewScreenWidth = false

[article]
  showDate = true
  #showViews = true
  #showLikes = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = true
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showSummary = true
  sharingLinks = false
  showComments = false

[list]
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true

[firebase]
  # apiKey = "XXXXXX"
  # authDomain = "XXXXXX"
  # projectId = "XXXXXX"
  # storageBucket = "XXXXXX"
  # messagingSenderId = "XXXXXX"
  # appId = "XXXXXX"
  # measurementId = "XXXXXX"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
